### ISSUE TITLE
Incorrect outputs when there is no Central Solenoid

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1494]
In GitLab by @mkovari on Dec 3, 2021, 19:22

When no central solenoid is included all of the central solenoid outputs are still present, and some are non-zero!
```
 (step22010303)      Central Solenoid (M$)                                                                        25.27

 Central solenoid                             0.090           0.180   (ohcth)             

No central solenoid included

 Summary of volt-second consumption by circuit (Wb) :
 
 circuit       BOP            BOF            EOF
 
     1        0.000          2.744          2.744
     2        0.000          2.744          2.744
     3        0.000        -21.012        -21.012
     4        0.000        -21.012        -21.012
     5        0.000         -7.567         -7.567
     6        0.000         -7.567         -7.567
 CS coil      0.000         -7.567         -7.567

 Ratio of central solenoid current at beginning of Pulse / end of flat-to (fcohbop)                 9.000E-01     
 Ratio of central solenoid current at beginning of Flat-top / end of flat (fcohbof)                 1.000E+00  OP 

 CS Circuit  - Time point 01 (A)                                          (cst01)                  -0.000E+00     
 CS Circuit  - Time point 02 (A)                                          (cst02)                   0.000E+00     
 CS Circuit  - Time point 03 (A)                                          (cst03)                  -4.802E+06     
 CS Circuit  - Time point 04 (A)                                          (cst04)                  -4.802E+06     
 CS Circuit  - Time point 05 (A)                                          (cst05)                  -4.802E+06     
 CS Circuit  - Time point 06 (A)                                          (cst06)                  -0.000E+00     

 CS ramp-up time burns (s)                                                (tramp.)                  4.428E+01  

 Initial charge time for CS from zero current (s)                         (tramp)                      44.277    
 Reset time to zero current for CS (s)                                    (tqnch)                      44.277       
```

**Comment by ym1906** [comment]
I believe this was resolved by @chris-ashe two years ago.

**Comment by grmtrkngtn** [comment]
Yes, I can now verify this is still an issue. I have made a branch to resolve this and pushed some commits.

Added some guards to outputs in PF Coils so CS variables aren't printed.

Added some guards in build to change radial build calc when no CS, and to guard outputs.

**Comment by grmtrkngtn** [comment]
I've done the quick fix for this, which is add a guard to radial build calculation and then mostly guard against outputs being printed.

_really_ we should stop all cs calculations from even being done in the first place - but this will require a fair refactor of pfcoil.py and more than this papercut sprint.

**Comment by chris-ashe** [comment]
The `iohcl` switch for the CS is a but of a blur. The CS will always exist physically in the radial build so it is always present. It should really be set up for which parts of the pulse it is used for. Eg, flat top only or ramp up and flat top

**Comment by grmtrkngtn** [comment]
After discussion in papercuts meeting, I've created a more comprehensive issue #4205 to comprehensively resolve this issue from the ground up. 

I'll close this issue as a result.
